server:
  port: 8888

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/api/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

keycloak:
  realm: mini-projet
  auth-server-url: http://keycloak:8080
  resource: api-gateway
  public-client: true
  bearer-only: true
