server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/productdb
    username: product
    password: product
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

keycloak:
  realm: mini-projet
  auth-server-url: http://localhost:8080
  resource: product-service
  public-client: true
  bearer-only: true
